name: Python ETL Pipeline
 
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
 
jobs:
  test:
    name: Tests (Python ${{ matrix.python-version }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        # 3.13 est récent; on teste aussi 3.12/3.11 pour la compatibilité
        python-version: ["3.13", "3.12", "3.11"]
 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
 
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"
 
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            pip install pytest pandas numpy
          fi
 
      - name: Show versions
        run: |
          python -V
          pip -V
          python - << 'PY'
          import sys, pandas as pd, numpy as np
          print("pandas:", pd.__version__)
          print("numpy :", np.__version__)
          PY
 
      - name: Run tests
        run: pytest -v